# Generated by Django 3.0.8 on 2020-08-02 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='imageURL',
            new_name='imageURL1',
        ),
    ]
