# Generated by Django 3.0.8 on 2020-08-02 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200801_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='installments',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_installments',
        ),
    ]
