# Generated by Django 3.0.8 on 2020-08-02 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_order_ordered_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='total_installments',
            new_name='total_installment',
        ),
    ]
