# Generated by Django 3.0.8 on 2020-08-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200803_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
