# Generated by Django 3.0.8 on 2020-08-04 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200804_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='creation_date',
            new_name='deletion_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='deletion_date',
        ),
    ]
