# Generated by Django 3.0.8 on 2020-08-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_address_address_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='total_installment',
            new_name='installment_amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='pending',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
